### ISSUE TITLE
Error messages are malformed when displayed to users

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#50]
![image](https://user-images.githubusercontent.com/605906/45633388-810e0900-ba54-11e8-9d74-b5eaa745c752.png)

@lediur Let's talk through how we want to surface error messages to users. The above is a bit raw more my liking, but I understand the prototype nature of what we currently have shipped.

**Comment by dlukeomalley** [comment]
Seen this morning on https://github.com/paypal/paypal-checkout

![image](https://user-images.githubusercontent.com/605906/46163868-415bd400-c241-11e8-80b1-
07845761e438.png)

**Comment by ulziibay** [comment]
Yeah. Not sure when this happens. @lediur what does the stack indicate?

**Comment by ulziibay** [comment]
Basically this happens when we have no /package end point results to show: aka: /repo returns some commits, and /package returns empty thing
https://api.secarta.io/v1/repo/github.com/paypal/paypal-checkout
https://api.secarta.io/v1/package/github.com/paypal/paypal-checkout
Repros on https://github.com/grvcoelho/lint-diff
